created hero button
SoftRyzen-internship/pure-water pull request #10
Opened 2023-09-21 07:09 UTC by Olenteva74

Добрый день, 
компонент можно использовать в Hero и в секции "Актуальний збір"

2023-09-21 07:57 UTC, nadiakhoptiuk requested changes

2023-09-21 07:57 UTC, nadiakhoptiuk commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +    'flex justify-center items-center gap-2 rounded-10',
тут можна всі рядки одним записати одразу, не потрібно потім робити join

2023-09-21 07:57 UTC, nadiakhoptiuk commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +  section: PropTypes.oneOf(['hero', 'currentFundraising']),
пропси обовязкові

2023-09-21 07:57 UTC, nadiakhoptiuk commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +      {children}
нам тут не потрібні children, потрібно додати свг краплі і спан як текст, текст для цих секцій однаковий. 

я б адаптувала цей компонент і для кнопки для табів - тоді треба розширити масив пропсів section і в залежності від цього повернути тег a з відповідним текстом

2023-09-21 08:18 UTC, BogdanGlazkov requested changes

2023-09-21 08:18 UTC, BogdanGlazkov commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +'use client';
Після use client відступ

2023-09-21 08:18 UTC, BogdanGlazkov commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +  return (
Відступ перед return

2023-09-21 08:18 UTC, BogdanGlazkov commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +      {children}
Якщо текст та іконка не змінюються, можна одразу прописати їх тут, а не прокидати

2023-09-21 08:18 UTC, BogdanGlazkov commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +  ];
Перенести ці стилі в компонент, щоб було зручніше перевіряти. 
Щоб розбити 1 довгу строку на переноси, використовуй Alt+Z

2023-09-21 08:18 UTC, BogdanGlazkov commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +    'opacity-90 hover:opacity-100 focus:opacity-100 transition-opacity cursor-pointer',
opacity не на всю кнопку, а лише на фон. Плюс на синьому фоні opacity має трохи інше значення

2023-09-21 08:18 UTC, BogdanGlazkov commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +  children: PropTypes.node,
children тут і в пропсах не треба, контент не змінюється

2023-09-21 08:52 UTC, Olenteva74 commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +    currentFundraising: 'bg-gradient-to-b from-sky-500 to-sky-700 text-white',
Заменила

2023-09-21 08:54 UTC, Olenteva74 commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +'use client';
Отступ добавила

2023-09-21 08:54 UTC, Olenteva74 commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +  return (
Отступ добавила

2023-09-21 09:12 UTC, Olenteva74 commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +  ];
Стили перенесла в компонент

2023-09-21 09:21 UTC, Olenteva74 commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +    'opacity-90 hover:opacity-100 focus:opacity-100 transition-opacity cursor-pointer',
Добавила bg-opacity, для синей кнопки bg-opacity-75

2023-09-21 09:45 UTC, Olenteva74 commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +    'opacity-90 hover:opacity-100 focus:opacity-100 transition-opacity cursor-pointer',
Старый синтаксис bg-opacity не работает, новый синтаксис bg-white/90. Для синей кнопки применяются стили, если прописать bg-gradient-to-b from-sky-500/75 to-sky-700/75,
 hover:iconGradient применяется, 
iconGradient/75 - фон не применяется, работает только iconGradient + opacity-75

2023-09-21 09:52 UTC, Olenteva74 commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +      {children}
Убрала children, добавила <span>{title}</span>.
Пока добавила пустой svg, после добавлю иконку, когда добавим иконки в проект

2023-09-21 09:53 UTC, Olenteva74 commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +  children: PropTypes.node,
Убрала children, добавила {title}.
Пока добавила пустой svg, после добавлю иконку, когда добавим иконки в проект

2023-09-21 09:55 UTC, Olenteva74 commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +    'flex justify-center items-center gap-2 rounded-10',
Стили прописала одной строкой и добавила в компонент

2023-09-21 09:56 UTC, Olenteva74 commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +  section: PropTypes.oneOf(['hero', 'currentFundraising']),
Пропсы поменяла на обязятельные

2023-09-21 09:58 UTC, Olenteva74 commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +      {children}
Убрала children, текст прописала сразу, иконку позже добавлю, когда добавим иконки в проект

2023-09-21 11:46 UTC, BogdanGlazkov approved these changes

2023-09-22 13:57 UTC, nadiakhoptiuk approved these changes

2023-09-22 13:57 UTC, merged