added nav bar for header/footer/menu
SoftRyzen-internship/pure-water pull request #11
Opened 2023-09-21 10:54 UTC by yuliahalaniuk

2023-09-21 12:51 UTC, BogdanGlazkov requested changes

2023-09-21 12:51 UTC, BogdanGlazkov commented on src/app/[lang]/layout.jsx
>          <main className="flex min-h-screen flex-col items-center justify-between">
Деструктуризовати staticPageData вище в коді

2023-09-21 12:51 UTC, BogdanGlazkov commented on src/components/NavBar/NavBar.jsx
> +                className={`${getFontWeight()} text-white/75 py-3 transition-colors cursor-pointer hover:text-white focus:text-white`}
Додати duration-300

2023-09-21 12:51 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
>          <p>{data}</p>
Це вже можна прибрати

2023-09-21 12:51 UTC, BogdanGlazkov commented on src/app/[lang]/layout.jsx
> +        <Header data={staticPageData.title} navArray={staticPageData.nav} />
data вже не потрібна

2023-09-21 12:57 UTC, BogdanGlazkov requested changes

2023-09-21 12:57 UTC, BogdanGlazkov commented on src/components/NavBar/NavBar.jsx
> +    header: 'flex-row gap-6 items-center justify-center',
hidden xl:flex

2023-09-21 12:57 UTC, BogdanGlazkov commented on src/components/NavBar/NavBar.jsx
> +    footer: 'flex-col gap-2 items-end',
hidden xl:flex

2023-09-21 12:57 UTC, BogdanGlazkov commented on src/components/NavBar/NavBar.jsx
> +    menu: 'flex-col gap-[23px] items-center',
flex xl:hidden

2023-09-21 14:36 UTC, nadiakhoptiuk requested changes

2023-09-21 14:36 UTC, nadiakhoptiuk commented on src/components/NavBar/NavBar.jsx
> +    section === 'header' ? 'font-medium' : 'font-light';
цей код краще написати одразу у стилях, щоб не реєструвати і не запускати колбек дарма

2023-09-21 14:36 UTC, nadiakhoptiuk commented on src/components/NavBar/NavBar.jsx
> +  const sortedArray = () => {
оскільки у нас все одно клієнтський компонент, краще маніпулювати даними через useState i useEffect чи useLayoutEffect

2023-09-21 14:36 UTC, nadiakhoptiuk commented on dictionaries/en.json
> -      "label": "Main",
потрібно в en i uk прибрати зайвий title - it is header

2023-09-21 14:36 UTC, nadiakhoptiuk commented on src/components/NavBar/NavBar.jsx
> +                to={id}
додати href="/" для фокусування з клавіатури

2023-09-22 07:46 UTC, BogdanGlazkov approved these changes

2023-09-25 10:35 UTC, nadiakhoptiuk requested changes

2023-09-25 10:35 UTC, nadiakhoptiuk commented on src/components/NavBar/NavBar.jsx
> +  const [sortedNavArray, setSortedNavArray] = useState([]);
краще початкове значення null

також перевірити букву Є:
https://prnt.sc/2R89oyfRO7Lr

2023-09-26 06:34 UTC, nadiakhoptiuk approved these changes

2023-09-26 06:34 UTC, merged