Created localization switcher
SoftRyzen-internship/pure-water pull request #12
Opened 2023-09-21 14:32 UTC by yuliahalaniuk

2023-09-21 15:02 UTC, nadiakhoptiuk requested changes

2023-09-21 15:02 UTC, nadiakhoptiuk commented on src/components/LocaleSwitcher/LocaleSwitcher.jsx
> +          href={redirectedPathName(isUkSet() ? 'en' : 'uk')}
писати це все руками не варто, ви повинні вчитись тому, що завтра клієнт додасть ще 1 локаль і весь цей код треба буде переписувати заново.
краще взяти змінні із файлу i18n і мепнути їх

2023-09-21 18:12 UTC, BogdanGlazkov requested changes

2023-09-21 18:12 UTC, BogdanGlazkov commented on src/components/LocaleSwitcher/LocaleSwitcher.jsx
> +      aria-label="language switcher"
aria-label має бути 2 мовами, це можна додати у json і прокинути пропсами

2023-09-22 14:06 UTC, nadiakhoptiuk commented on src/components/LocaleSwitcher/LocaleSwitcher.jsx
> +
він усе ще скаче, потрібно додати абсолют

2023-09-22 14:26 UTC, nadiakhoptiuk requested changes

2023-09-22 14:26 UTC, nadiakhoptiuk commented on src/components/LocaleSwitcher/LocaleSwitcher.jsx
> +      <Listbox.Button className="flex gap-1 items-center">
при фокусі некрасиво виглядає:
додай w-full h-full py-2 px-4

2023-09-22 14:26 UTC, nadiakhoptiuk commented on src/components/LocaleSwitcher/LocaleSwitcher.jsx
> +      className=" flex flex-col gap-2 py-2 px-4 w-[65px] text-white rounded-20 switcherGradient hover:switcherGradientActive focus:switcherGradientActive transition duration-300 backdrop-blur-[1px] c
py-2 px-4 прибрати

2023-09-22 14:26 UTC, nadiakhoptiuk commented on src/components/LocaleSwitcher/LocaleSwitcher.jsx
> +          <Listbox.Option
додати на опцію і на список опції as="div", щоб у нас не було списку з одного елемента

2023-09-22 14:26 UTC, nadiakhoptiuk commented on src/components/LocaleSwitcher/LocaleSwitcher.jsx
> +            className="w-full text-xs/[9px] uppercase font-light "
text-xs/[9px] - щось такого не бачила раніше, 
тут треба буде підкорегувати стилі після змін, перевірити фокусування

2023-09-26 07:28 UTC, nadiakhoptiuk approved these changes

2023-09-26 07:29 UTC, merged