Feature/hero section
SoftRyzen-internship/pure-water pull request #14
Opened 2023-09-22 12:09 UTC by Olenteva74

Добрый день, 
отправляю на проверку секцию Hero.
Я создала компонент SocialLinks для иконок соц-сетей, его можно использовать и в футере.
Кнопку-ссылку поместила в div с бекграундом, теперь все отображается

2023-09-22 14:27 UTC, BogdanGlazkov requested changes

2023-09-22 14:27 UTC, BogdanGlazkov commented on src/app/[lang]/page.jsx
> +      />
Зробити деструктуризацію staticPageData вище у коді

2023-09-22 14:27 UTC, BogdanGlazkov commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +import React, { useState } from 'react';
React імпортувати не потрібно

2023-09-22 14:27 UTC, BogdanGlazkov commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +import PropTypes from 'prop-types';
Відступ між зовнішніми та внутрішніми імпортами

2023-09-22 14:27 UTC, BogdanGlazkov commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +      )}
Стилі однакові, міняється лише іконка. Тому зробити рендер за умовою всередині спана. І щоб було зрозуміліше, краще використати оператор &&, а не тернарники

2023-09-22 14:27 UTC, BogdanGlazkov commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +  section: PropTypes.oneOf(['hero', 'currentFundraising']).isRequired,
Краще просто current

2023-09-22 14:27 UTC, BogdanGlazkov commented on src/components/SocialLinks/SocialLinks.jsx
> +import React from 'react';
React завжди йде першим у імпортах

2023-09-22 14:27 UTC, BogdanGlazkov commented on src/sections/Hero/Hero.jsx
> +
Відокремити відступом зовнішні та внутрішні імпорти

2023-09-22 14:51 UTC, BogdanGlazkov requested changes

2023-09-22 14:51 UTC, BogdanGlazkov commented on src/sections/Hero/Hero.jsx
> +          </h1>
У файлі json замінити українську І на англійську, бо вона дуже висока https://prnt.sc/JN0e1HfcsN74

2023-09-23 10:29 UTC, Olenteva74 commented on src/sections/Hero/Hero.jsx
> +          </h1>
Заменила

2023-09-23 11:57 UTC, Olenteva74 commented on src/app/[lang]/page.jsx
> +      />
const {hero, makeDonate, socials} = staticPageData;

 heroData={hero}
 titleBtn={makeDonate.title}
 socials={socials.links}

2023-09-23 11:58 UTC, Olenteva74 commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +import React, { useState } from 'react';
Код изменен

2023-09-23 11:59 UTC, Olenteva74 commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +import PropTypes from 'prop-types';
Ок

2023-09-23 11:59 UTC, Olenteva74 commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +      )}
Код изменен

2023-09-23 12:00 UTC, Olenteva74 commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +  section: PropTypes.oneOf(['hero', 'currentFundraising']).isRequired,
Ок,
section: PropTypes.oneOf(['hero', 'current']).isRequired,

2023-09-23 12:01 UTC, Olenteva74 commented on src/sections/Hero/Hero.jsx
> +
import PropTypes from 'prop-types';

import { Container } from '@/components/Container';

2023-09-23 12:01 UTC, Olenteva74 commented on src/sections/Hero/Hero.jsx
> +  return (
Ок

2023-09-23 12:10 UTC, Olenteva74 commented on src/sections/Hero/Hero.jsx
> +          <div className="bg-white/90 hover:bg-white/100 focus:bg-white/100 rounded-10">
Изменился код кнопки, этот <div className="bg-white/90 hover:bg-white/100 focus:bg-white/100 rounded-10"> я убрала

2023-09-23 12:12 UTC, Olenteva74 commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +      'bg-gradient-to-b from-sky-500/75 to-sky-700/75 hover:iconGradient focus:iconGradient text-white',
Ок

2023-09-25 07:26 UTC, BogdanGlazkov approved these changes

2023-09-25 14:59 UTC, nadiakhoptiuk requested changes

2023-09-25 14:59 UTC, nadiakhoptiuk commented on src/sections/Hero/Hero.jsx
> +    <section className="w-screen hero-bg-tab xl:hero-bg-desk pt-[134px] pb-[121px] md:pt-28 md:pb-[78px] xl:pt-[126px] xl:pb-[140px] text-white">
на десктопі завантажується hero-bg-tab і картинки по цьому класу. 
треба назвати просто hero-bg або hero-section, і в css через медіаправила написати для цього класу різні фони, бо такий підхід не працює

2023-09-25 16:24 UTC, nadiakhoptiuk requested changes

2023-09-25 16:24 UTC, nadiakhoptiuk commented on src/components/SocialLinks/SocialLinks.jsx
> +              className="flex justify-center items-center gap-3"
треба зробити лінки на всю висоту/ширину лішок на таблеті і мобілці,
прибрати gap

а на декстопі gap має бути 16, а ширина лішки/ссилки - 24

2023-09-25 16:24 UTC, nadiakhoptiuk commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +  section: PropTypes.oneOf(['hero', 'current']).isRequired,
це не зрозуміло, яка секція, залиш як було)

і потрібно виправити у стилях кнопки (де вона біла) - там опасіті 0,9, а не 0,75

2023-09-25 16:24 UTC, nadiakhoptiuk commented on src/components/SocialLinks/SocialLinks.jsx
> +            className={`${styledLink[section]} text-white/75 hover:text-white focus:text-white transition duration-300`}
ховер і фокус ми ставимо не на лішку, а на посилання (інтерактивний елемент)

2023-09-25 16:24 UTC, nadiakhoptiuk commented on src/sections/Hero/Hero.jsx
> +          <div className="flex flex-col items-center gap-1 md:flex-row-reverse md:gap-6 mb-1 md:mb-6 xl:mb-[28px]">
на таблеті відступ вниз - 16 пікс

висота цього діва на десктопі - 38 (поправити)

2023-09-26 09:29 UTC, Olenteva74 commented on src/sections/Hero/Hero.jsx
> +    <section className="w-screen hero-bg-tab xl:hero-bg-desk pt-[134px] pb-[121px] md:pt-28 md:pb-[78px] xl:pt-[126px] xl:pb-[140px] text-white">
Создала класс hero, написала медиа-правила

2023-09-26 09:41 UTC, Olenteva74 commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +  section: PropTypes.oneOf(['hero', 'current']).isRequired,
Исправила

2023-09-26 11:41 UTC, Olenteva74 commented on src/sections/Hero/Hero.jsx
> +          <div className="flex flex-col items-center gap-1 md:flex-row-reverse md:gap-6 mb-1 md:mb-6 xl:mb-[28px]">
Размеры поправила

2023-09-26 12:52 UTC, nadiakhoptiuk requested changes

2023-09-26 12:52 UTC, nadiakhoptiuk commented on src/components/SocialLinks/SocialLinks.jsx
> +    'aria-label': PropTypes.string.isRequired,
в json файлі усі ключі повинні бути camelCase, щоб все добре працювало, потрібно замінити тут і у файлі

2023-09-26 12:52 UTC, nadiakhoptiuk commented on src/components/SocialLinks/SocialLinks.jsx
> +              aria-label={social['aria-label']}
тут також замінити на ariaLabel

2023-09-26 13:01 UTC, Olenteva74 commented on src/components/SocialLinks/SocialLinks.jsx
> +    'aria-label': PropTypes.string.isRequired,
Заменила

2023-09-26 13:34 UTC, nadiakhoptiuk approved these changes

2023-09-26 13:35 UTC, merged