Add projects section
SoftRyzen-internship/pure-water pull request #16
Opened 2023-09-25 07:54 UTC by Anna-Voronina

2023-09-25 09:28 UTC, BogdanGlazkov requested changes

2023-09-25 09:28 UTC, BogdanGlazkov commented on src/components/ProjectListItem/ProjectListItem.jsx
> +        className="relative rounded-[20px] overflow-hidden mb-3 md:mb-4"
rounded-[20px] замінити на rounded-20 (ця змінна є у файлі конфіг)

2023-09-25 09:28 UTC, BogdanGlazkov commented on src/components/ProjectListItem/ProjectListItem.jsx
> +  staticData,
Навіщо передавати всі дані у staticData, якщо потрібно тільки projects

2023-09-25 09:28 UTC, BogdanGlazkov commented on src/components/ProjectListItem/ProjectListItem.jsx
> +};
Описати всі проптайпси

2023-09-25 09:28 UTC, BogdanGlazkov commented on src/sections/Projects/Projects.jsx
> +
Розділити зовнішні та внутрішні імпорти

2023-09-25 09:28 UTC, BogdanGlazkov commented on src/components/ProjectsWrapper/ProjectsWrapper.jsx
> +
Розділити зовнішні та внутрішні імпорти

2023-09-25 09:28 UTC, BogdanGlazkov commented on src/components/ProjectsWrapper/ProjectsWrapper.jsx
> +      <SectionTitle title={staticData.projects.title} />
staticData прибрати

2023-09-25 09:55 UTC, BogdanGlazkov requested changes

2023-09-25 09:55 UTC, BogdanGlazkov commented on src/components/ProjectListItem/ProjectListItem.jsx
> +        />
Теги Image повинні мати атрибути width, height та quality={100}

2023-09-25 09:55 UTC, BogdanGlazkov commented on src/components/ProjectListItem/ProjectListItem.jsx
> +        />
Картинки на макеті трохи ширші

2023-09-25 09:57 UTC, BogdanGlazkov requested changes

2023-09-25 09:57 UTC, BogdanGlazkov commented on src/components/ProjectListItem/ProjectListItem.jsx
> +          layout="fill"
У консолі є попередження: Image has legacy prop "layout"

2023-09-25 16:57 UTC, BogdanGlazkov requested changes

2023-09-25 16:57 UTC, BogdanGlazkov commented on src/sections/Projects/Projects.jsx
> +    </section>
Імпортувати контейнер

2023-09-25 16:57 UTC, BogdanGlazkov commented on src/components/ProjectSwiper/ProjectSwiper.jsx
> +    <div>
Чи потрібна тут зайва обгортка?

2023-09-25 16:57 UTC, BogdanGlazkov commented on src/components/ProjectsWrapper/ProjectsWrapper.jsx
> +      <SectionTitle title={staticData.projects.title} />
SectionTitle краще перенести у секцію

2023-09-25 17:02 UTC, BogdanGlazkov requested changes

2023-09-25 17:02 UTC, BogdanGlazkov commented on src/sections/Projects/Projects.jsx
> +    <section className="flex flex-col gap-y-6 xl:gap-y-8 max-w-[320px] md:max-w-3xl xl:max-w-7xl mx-auto px-5 md:px-9 xl:px-6 py-[30px] md:py-10 xl:py-20">
Імпортувати клас section з файла css.
Прибрати зайві стилі (марджини, падінги) після додавання контейнера. 
flex тут також не потрібен

2023-09-26 08:44 UTC, BogdanGlazkov requested changes
Змерджити з dev, пофіксити конфлікти

2023-09-26 08:44 UTC, BogdanGlazkov commented on src/components/ProjectOverlay/ProjectOverlay.jsx
> +    overlay: PropTypes.string.isRequired,
Залишити тільки те, що використовується

2023-09-26 09:21 UTC, nadiakhoptiuk requested changes

2023-09-26 09:21 UTC, nadiakhoptiuk commented on src/components/GalleryModal/GalleryModal.jsx
> +import 'swiper/css';
стилі потрібно підключати завжди в кінці імпортів

2023-09-26 09:21 UTC, nadiakhoptiuk commented on src/components/ProjectSwiperNav/ProjectSwiperNav.jsx
> +  variant: PropTypes.string,
прописати які можуть бути variants - масивом

2023-09-26 09:21 UTC, nadiakhoptiuk commented on src/components/ProjectSwiperNav/ProjectSwiperNav.jsx
> +        {variant === 'cards' && <PrevIcon className="w-8 h-8" />}
Prev i Next icon - 

потрібно зробити таку кнопку не активну, а при ховері:
https://prnt.sc/ikUVJkGXjn4j

а якщо слайд останній чи перший, то треба питати дизайнера, я думаю, можна і сіреньку

2023-09-26 09:33 UTC, nadiakhoptiuk requested changes

2023-09-26 09:33 UTC, nadiakhoptiuk commented on src/components/GalleryModal/GalleryModal.jsx
> +                  src={image.url}
тут треба спробувати забирати secure_url (і по аналогії скрізь)
але в налаштуваннях доменів змінити на https

2023-09-27 12:00 UTC, BogdanGlazkov requested changes

2023-09-27 12:00 UTC, BogdanGlazkov commented on src/sections/Projects/Projects.jsx
> +export const Projects = async ({ lang, projects }) => {
Описати projects проптайпси

2023-09-27 12:16 UTC, BogdanGlazkov requested changes

2023-09-27 12:16 UTC, BogdanGlazkov commented on src/components/ProjectSwiper/ProjectSwiper.jsx
> +      >
Добре, але на мобільному все ж таки не видно край другої картки. Треба ще трохи підправити https://prnt.sc/UeimKAOtdkUy

2023-09-27 12:23 UTC, BogdanGlazkov requested changes

2023-09-27 12:23 UTC, BogdanGlazkov commented on src/components/ProjectSwiper/ProjectSwiper.jsx
> +          disabledClass: 'opacity-30 cursor-not-allowed',
Може замінити на cursor-none, бо червоний знак трохи очі ріже

2023-09-28 07:56 UTC, nadiakhoptiuk requested changes

2023-09-28 07:56 UTC, nadiakhoptiuk commented on src/components/ProjectOverlay/ProjectOverlay.jsx
> +      className={`project-overlay absolute top-0 left-0 w-full h-full hidden xl:flex flex-col justify-center items-center bg-gradient-to-b from-[#20b1e2bf] to-[#0f5598bf] backdrop-blur-[12.5px] ${sty
тут transition-300

2023-09-28 07:57 UTC, BogdanGlazkov approved these changes

2023-09-28 07:59 UTC, BogdanGlazkov commented on src/components/ProjectOverlay/ProjectOverlay.jsx
> +      className={`project-overlay absolute top-0 left-0 w-full h-full hidden xl:flex flex-col justify-center items-center bg-gradient-to-b from-[#20b1e2bf] to-[#0f5598bf] backdrop-blur-[12.5px] ${sty
duration-300?

2023-09-28 13:08 UTC, nadiakhoptiuk approved these changes

2023-09-28 13:08 UTC, merged