Feature/donate section
SoftRyzen-internship/pure-water pull request #17
Opened 2023-09-25 08:11 UTC by Olenteva74

Добрый день,
создала шаблон для вкладок

2023-09-25 13:07 UTC, BogdanGlazkov requested changes

2023-09-25 13:07 UTC, BogdanGlazkov commented on src/components/Tabs/Tabs.jsx
> +          <li
Фігурні дужки та  return можна прибрати, буде менше кода)

2023-09-25 13:07 UTC, BogdanGlazkov commented on src/components/Tabs/Tabs.jsx
> +      {tabs.map(tab => {
Тут можна деструктуризувати tab:  tabs.map( {label} =>

2023-09-25 13:07 UTC, BogdanGlazkov commented on src/sections/Donate/Donate.jsx
> +};
Не забуваємо проптайпси

2023-09-25 13:12 UTC, BogdanGlazkov requested changes

2023-09-25 13:12 UTC, BogdanGlazkov commented on src/app/[lang]/globals.css
> +    @apply tabLink border-2 border-sky-500 group-hover/tab:border-0 group-focus-within/tab:border-0  group-hover/tab:bg-gradient-to-b from-sky-500 to-sky-800 group-focus-within/tab:bg-gradient-to-b f
from-sky-500 to-sky-800 повторюється

2023-09-25 13:12 UTC, BogdanGlazkov commented on src/components/TabLinks/TabLinks.jsx
> +  }, []);
Додати залежності. В тебе так не підкреслює? https://prnt.sc/5JV1QkkTbovg

2023-09-25 13:17 UTC, BogdanGlazkov requested changes

2023-09-25 13:17 UTC, BogdanGlazkov commented on src/sections/Donate/Donate.jsx
> +    <section id="donate" className="w-screen bg-white">
Додати клас section з css файла

2023-09-26 11:32 UTC, nadiakhoptiuk commented
тут 30 файлів! я просила створювати гілки з dev для різних тасок, а не зі своїх гілок.. і це прописано в інструкції

2023-09-27 09:10 UTC, closed without merging

2023-09-27 09:10 UTC, nadiakhoptiuk commented
closed because new pull request was created