Created Logo
SoftRyzen-internship/pure-water pull request #18
Opened 2023-09-25 09:15 UTC by yuliahalaniuk

2023-09-25 11:51 UTC, BogdanGlazkov approved these changes

2023-09-25 11:51 UTC, BogdanGlazkov commented on dictionaries/en.json
> +  "logoText": "CLEAN WATER FOR EVERYONE",
Уточнити у дизайнера, чи буде лого мінятися залежно від мови. Зазвичай лого не міняється

2023-09-25 11:51 UTC, BogdanGlazkov commented on dictionaries/uk.json
> +  "logoText": "ЧИСТА ВОДА ВСІМ",
Якщо logoText буде перекладатися, все що до нього відноситься взяти в один об'єкт logo з ключами aria та text

2023-09-25 11:56 UTC, BogdanGlazkov requested changes

2023-09-25 11:56 UTC, BogdanGlazkov commented on src/components/Logo/Logo.jsx
> +      className={`${fontVariable} flex gap-2 items-center`}
fontVariable - ця змінна тут напевно не потрібна

2023-09-26 11:30 UTC, nadiakhoptiuk requested changes

2023-09-26 11:30 UTC, nadiakhoptiuk commented on src/components/Logo/Logo.jsx
> +  const currentLocale = usePathname().split('/')[1];
краще прокинути lang з хедера, ніж запускати в кожному компоненті хук

2023-09-26 11:30 UTC, nadiakhoptiuk commented on src/components/Logo/Logo.jsx
> +      className="block w-[90px] h-[48px] xl:w-[92px] xl:h-[54px] text-white/75 hover:text-white transition-colors duration-300 "
focus потрібно додавати

2023-09-27 08:32 UTC, nadiakhoptiuk approved these changes

2023-09-27 08:32 UTC, merged