add current fundraising section
SoftRyzen-internship/pure-water pull request #19
Opened 2023-09-26 12:55 UTC by Anna-Voronina

2023-09-26 14:17 UTC, BogdanGlazkov requested changes

2023-09-27 08:09 UTC, nadiakhoptiuk requested changes

2023-09-27 08:09 UTC, nadiakhoptiuk commented on src/sections/CurrentFundraising/CurrentFundraising.jsx
> +        <div className="flex justify-center items-center xl:hidden">
ця обгортка зайва, перенеси стилі на div у MakeDonateBtn, центрувати блоковий елемент можна без флексів mx-auto

2023-09-27 08:09 UTC, nadiakhoptiuk commented on src/sections/CurrentFundraising/CurrentFundraising.jsx
> +        <SectionTitle title={fundraising?.title} />
відступи від заголовка до контенту секції повинні бути вказані в цьому компоненті, щоб кожен у секціях не писав їх
можеш перевірити відступи на всіх секціях та девайсах і перенести?

2023-09-28 08:11 UTC, BogdanGlazkov approved these changes

2023-09-28 13:26 UTC, nadiakhoptiuk requested changes

2023-09-28 13:26 UTC, nadiakhoptiuk commented on src/components/MakeDonateBtn/MakeDonateBtn.jsx
> +export const MakeDonateBtn = ({ title, section, currentFundClassName }) => {
тут треба додати значення за умовчуванням (пустий рядок), бо пропс не обовязковий, буде писати в класі undefined

2023-09-29 08:53 UTC, nadiakhoptiuk approved these changes

2023-09-29 08:53 UTC, nadiakhoptiuk commented on src/components/ProjectListItem/ProjectListItem.jsx
> +          loading="lazy"
це не варто додавати, некст автоматично їх робить lazy,
в наст пулреквестах будемо гратися з плейсхолдерами

2023-09-29 08:55 UTC, merged