update dictionaries
SoftRyzen-internship/pure-water pull request #20
Opened 2023-09-26 18:09 UTC by Olenteva74

Тестовый коммит

2023-09-27 08:31 UTC, BogdanGlazkov requested changes

2023-09-27 08:31 UTC, BogdanGlazkov commented on src/components/Tabs/Tabs.jsx
> +          <li
Якщо повертаємо один елемент, фігурні дужки та return можна не писати

2023-09-27 08:31 UTC, BogdanGlazkov commented on src/app/[lang]/globals.css
> +    @apply tabLink border-2 border-tabBorderColor group-hover/tab:border-0 group-focus-within/tab:border-0  group-hover/tab:tabLinkGradient group-focus-within/tab:tabLinkGradient transition-colors du
Мабуть не transition-colors, а просто  transition, бо там ще й бордер змінюється

2023-09-27 08:31 UTC, BogdanGlazkov commented on src/app/[lang]/globals.css
> +    @apply textGradient text-transparent bg-clip-text font-medium group-hover/tab:font-semibold group-focus-within/tab:font-semibold group-hover/tab:text-white group-focus-within/tab:text-white trans
Просто transition

2023-09-27 08:31 UTC, BogdanGlazkov commented on tailwind.config.js
> +        tabBorderColor: '#1E9FD4',
Змість цього можна використати primary, це практично той самий колір

2023-09-27 08:31 UTC, BogdanGlazkov commented on src/sections/Donate/Donate.jsx
> +  }),
В кінці не вистачає три isRequired

2023-09-27 08:31 UTC, BogdanGlazkov commented on src/components/TabLinks/TabLinks.jsx
> +  }, []);
Додати залежності у масив

2023-09-27 08:56 UTC, BogdanGlazkov requested changes

2023-09-27 08:56 UTC, BogdanGlazkov commented on src/app/[lang]/globals.css
> +    background-image: linear-gradient(180deg, #1d9fd4 0%, #1674b1 100%);
Замість цього можна використати iconGradient, це практично той самий градієнт

2023-09-27 08:56 UTC, BogdanGlazkov commented on src/app/[lang]/globals.css
> +    background-image: linear-gradient(180deg, #1fb0e2 0%, #0f5598 100%);
Замість цього можна використати boxGradient, це практично той самий градієнт

2023-09-27 08:56 UTC, BogdanGlazkov commented on src/components/PaymentDetail/PaymentDetail.jsx
> +export const PaymentDetail = ({ title, description, isSwift }) => {
Якщо isSwift це необов'язковий пропс, задати йому значення за замовчуванням false

2023-09-27 08:56 UTC, BogdanGlazkov commented on src/components/TabContent/Mono/Mono.jsx
> +    }),
info і  link теж isRequired

2023-09-27 08:56 UTC, BogdanGlazkov commented on src/components/TabContent/PayPal/PayPal.jsx
> +  }),
info теж isRequired

2023-09-27 08:56 UTC, BogdanGlazkov commented on src/components/TabContent/Privat24/Privat24.jsx
> +};
Вчимо проптайпси. info,  card, link,  paymentDetails та shape (об'єкт) теж isRequired

2023-09-27 08:56 UTC, BogdanGlazkov commented on src/components/TabContent/Swift/Swift.jsx
> +            return (
Можна без фігурних дужок та return

2023-09-27 08:56 UTC, BogdanGlazkov commented on src/components/TabContent/Swift/Swift.jsx
> +              <li
Можна без фігурних дужок та return

2023-09-27 08:56 UTC, BogdanGlazkov commented on src/components/TabContent/Swift/Swift.jsx
> +};
Додати 5 isRequired

2023-09-27 08:56 UTC, BogdanGlazkov commented on src/components/TabLinks/TabLinks.jsx
> +            onClick={() => {
Можна без фігурних дужок, буде одною строкою і менше кода

2023-09-27 08:56 UTC, BogdanGlazkov commented on src/components/TabLinks/TabLinks.jsx
> +};
Додати 2 isRequired

2023-09-27 08:56 UTC, BogdanGlazkov commented on src/components/Tabs/Tabs.jsx
> +  ),
Додати 2 isRequired

2023-09-27 08:56 UTC, BogdanGlazkov commented on src/sections/Donate/Donate.jsx
> +        <div className="flex flex-col gap-6 xl:gap-8 justify-center items-center">
div прибрати, ці стилі перенести на контейнер. Для цього у контейнері можна додати необов'язковий пропс className=""

2023-09-27 08:56 UTC, BogdanGlazkov commented on src/sections/Donate/Donate.jsx
> +        <div className="flex flex-col gap-6 xl:gap-8 justify-center items-center">
flex тут не потрібен, на SectionTitle просто додати mb-6 xl:mb-8 (йому можна додати необов'язковий пропс className="", як і у контейнері)

2023-09-27 09:02 UTC, BogdanGlazkov requested changes

2023-09-27 09:02 UTC, BogdanGlazkov commented on src/components/PaymentDetail/PaymentDetail.jsx
> +          {copied ? <Check /> : <Copy />}
На ці іконки скрізь можна задати title (підказку при ховері) та aria-label, але це все вже треба прокинути через словник

2023-09-27 09:17 UTC, nadiakhoptiuk requested changes

2023-09-27 09:17 UTC, nadiakhoptiuk commented on src/components/PaymentLink/PaymentLink.jsx
> +        className="w-full textGradient text-transparent bg-clip-text flex gap-3 justify-center items-center before:w-6 before:h-6 before:flex before:justify-center before:items-start before:content-[
посилання повинно бути на 100% розмірів діва, при фокусуванні аутлайн невірно:
https://prnt.sc/DqcixGYuEOgD

падінги з діва перенести на посилання, або встановити розміри діву, а посиланню w-full h-full

2023-09-27 09:17 UTC, nadiakhoptiuk commented on src/components/TabLinks/TabLinks.jsx
> +  useEffect(() => {
навіщо додавати якірне посилання до url?
таби можна перемикати і без нього

2023-09-27 09:17 UTC, nadiakhoptiuk commented on src/app/[lang]/globals.css
> +    @apply tabLink border-2 border-tabBorderColor group-hover/tab:border-0 group-focus-within/tab:border-0  group-hover/tab:tabLinkGradient group-focus-within/tab:tabLinkGradient transition-colors du
при ховері/фокусі іде різка зміна фону кнопок, можна поставити опасіті-0 і анімувати його

2023-09-27 09:17 UTC, nadiakhoptiuk commented on src/components/TabLinks/TabLinks.jsx
> +            <a
замінити на кнопку.
можна використати бібліотеку headless ui за бажанням

2023-09-27 11:44 UTC, nadiakhoptiuk requested changes

2023-09-27 11:44 UTC, nadiakhoptiuk commented on src/components/PaymentDetail/PaymentDetail.jsx
> +          className="flex-none flex justify-center items-center w-10 md:w-12 xl:w-6 h-10 md:h-12 xl:h-6 opacity-75 hover:opacity-100 transition duration-300 cursor-pointer fill-none stroke-current"
треба зробити не дівом, а кнопкою, щоб табалось із клавіатури
розміри кнопки на моб 40х40, таб - 48х48б десктоп - 24х24

іконки мають також різні розміри на всіх девайсах (до того ж, copy має інші розміри, ніж check)

2023-09-27 11:44 UTC, nadiakhoptiuk commented on src/components/TabContent/Privat24/Privat24.jsx
> +export const Private24 = ({ info }) => {
компоненти табів та панелей повинні тягнутися до 480 
https://prnt.sc/RaDWMGGvf7MF

2023-09-27 11:44 UTC, nadiakhoptiuk commented on src/components/PaymentDetail/PaymentDetail.jsx
> +          {copied ? <Check /> : <Copy />}
тут виходить також, що по кліку на галочку у нас теж копіює, але не повинно

2023-09-27 18:57 UTC, Olenteva74 commented on src/components/Tabs/Tabs.jsx
> +          <li
У меня без return не работает

2023-09-27 19:01 UTC, Olenteva74 commented on src/app/[lang]/globals.css
> +    @apply tabLink border-2 border-tabBorderColor group-hover/tab:border-0 group-focus-within/tab:border-0  group-hover/tab:tabLinkGradient group-focus-within/tab:tabLinkGradient transition-colors du
Поставила  transition-all

2023-09-27 19:02 UTC, Olenteva74 commented on src/app/[lang]/globals.css
> +    @apply textGradient text-transparent bg-clip-text font-medium group-hover/tab:font-semibold group-focus-within/tab:font-semibold group-hover/tab:text-white group-focus-within/tab:text-white trans
Поставила transition-all, меняется еще font-weight

2023-09-27 19:03 UTC, Olenteva74 commented on tailwind.config.js
> +        tabBorderColor: '#1E9FD4',
Заменила

2023-09-27 19:04 UTC, Olenteva74 commented on src/sections/Donate/Donate.jsx
> +  }),
Добавила

2023-09-27 19:04 UTC, Olenteva74 commented on src/components/TabLinks/TabLinks.jsx
> +  }, []);
Этот код удалила

2023-09-27 19:05 UTC, Olenteva74 commented on src/app/[lang]/globals.css
> +    background-image: linear-gradient(180deg, #1d9fd4 0%, #1674b1 100%);
Изменила

2023-09-27 19:05 UTC, Olenteva74 commented on src/app/[lang]/globals.css
> +    background-image: linear-gradient(180deg, #1fb0e2 0%, #0f5598 100%);
Изменила

2023-09-27 19:12 UTC, Olenteva74 commented on src/components/TabContent/Mono/Mono.jsx
> +    }),
Добавила

2023-09-27 19:13 UTC, Olenteva74 commented on src/components/TabContent/PayPal/PayPal.jsx
> +  }),
Добавила

2023-09-27 19:13 UTC, Olenteva74 commented on src/components/TabContent/Swift/Swift.jsx
> +};
Добавила

2023-09-27 19:15 UTC, Olenteva74 commented on src/components/TabLinks/TabLinks.jsx
> +            onClick={() => {
Убрала

2023-09-27 19:16 UTC, Olenteva74 commented on src/components/TabLinks/TabLinks.jsx
> +};
Добавила

2023-09-27 19:17 UTC, Olenteva74 commented on src/components/Tabs/Tabs.jsx
> +  ),
Добавила

2023-09-27 19:23 UTC, Olenteva74 commented on src/sections/Donate/Donate.jsx
> +        <div className="flex flex-col gap-6 xl:gap-8 justify-center items-center">
Убрала

2023-09-27 19:23 UTC, Olenteva74 commented on src/components/PaymentDetail/PaymentDetail.jsx
> +          {copied ? <Check /> : <Copy />}
Добавила

2023-09-27 19:23 UTC, Olenteva74 commented on src/components/PaymentLink/PaymentLink.jsx
> +        className="w-full textGradient text-transparent bg-clip-text flex gap-3 justify-center items-center before:w-6 before:h-6 before:flex before:justify-center before:items-start before:content-[
Заменила на кнопки

2023-09-27 19:24 UTC, Olenteva74 commented on src/components/TabLinks/TabLinks.jsx
> +            <a
Заменила на кнопку

2023-09-27 19:26 UTC, Olenteva74 commented on src/components/PaymentDetail/PaymentDetail.jsx
> +          className="flex-none flex justify-center items-center w-10 md:w-12 xl:w-6 h-10 md:h-12 xl:h-6 opacity-75 hover:opacity-100 transition duration-300 cursor-pointer fill-none stroke-current"
Заменила copy на кнопку,  check оставила дивом

2023-09-27 19:35 UTC, Olenteva74 commented on src/components/PaymentDetail/PaymentDetail.jsx
> +          {copied ? <Check /> : <Copy />}
Добавила onClick только для Copy

2023-09-27 20:08 UTC, Olenteva74 commented on src/components/TabContent/Privat24/Privat24.jsx
> +export const Private24 = ({ info }) => {
у нас container 480px, поставила на всю ширину

2023-09-28 09:09 UTC, BogdanGlazkov requested changes

2023-09-28 09:10 UTC, BogdanGlazkov commented
Також треба стягнути dev і вирішити конфлікти

2023-09-28 09:39 UTC, BogdanGlazkov requested changes

2023-09-28 09:39 UTC, BogdanGlazkov commented on src/components/TabContent/Privat24/Privat24.jsx
> +        </h3>
Незрозумілий знак, може спробуй якось замінити https://prnt.sc/2fBaH3S_kPKd

2023-09-28 09:39 UTC, BogdanGlazkov commented on src/components/TabContent/Mono/Mono.jsx
> +    <div className="flex flex-col gap-10 justify-center items-center md:flex-row xl:flex-row-reverse xl:gap-0 md:justify-between">
На планшеті напевно макет змінився, там зараз як і на десктопі, кнопка має бути ліворуч https://prnt.sc/3o7E6hm0Wljl

2023-09-28 09:39 UTC, BogdanGlazkov commented on src/components/TabContent/Mono/Mono.jsx
> +        <PaymentLink title={link.title} url={link.url} />
На планшеті у кнопки-посилання білий фон і висота 80рх

2023-09-28 09:39 UTC, BogdanGlazkov commented on src/components/PaymentLink/PaymentLink.jsx
> +    <div className="w-full md:w-[447px] xl:w-[572px] py-4 px-11 md:py-6 md:px-10 rounded-10 text-base md:text-xl xl:text-[28px] font-medium leading-none cursor-pointer bg-white/90 hover:bg-white focu
На мобілці і планшеті колір білий

2023-09-28 09:55 UTC, BogdanGlazkov requested changes

2023-09-28 09:55 UTC, BogdanGlazkov commented on src/components/TabContent/Privat24/Privat24.jsx
> +        <ul className="flex flex-col gap-2 xl:gap-6">
Збільшити line-height

2023-09-28 09:55 UTC, BogdanGlazkov commented on src/components/TabContent/Privat24/Privat24.jsx
> +        <PaymentLink title={link.title} url={link.url} />
Збільшити висоту кнопки

2023-09-28 09:55 UTC, BogdanGlazkov commented on src/components/TabContent/Mono/Mono.jsx
> +        <PaymentLink title={link.title} url={link.url} />
На десктопі висота 93рх

2023-09-28 09:55 UTC, BogdanGlazkov commented on src/components/TabContent/Mono/Mono.jsx
> +        <QrCode />
На десктопі збільшити розміри

2023-09-28 09:55 UTC, BogdanGlazkov commented on src/components/TabContent/Swift/Swift.jsx
> +                className="flex flex-col gap-3 md:gap-4 xl:gap-3"
Збільшити line-height

2023-09-28 14:23 UTC, nadiakhoptiuk requested changes

2023-09-28 14:23 UTC, nadiakhoptiuk commented on src/components/PaymentDetail/PaymentDetail.jsx
> +          {copied ? (
треба щоб стейт змінювався через 3-5 секунд, наприклад, після копіювання, знову на false.

2023-09-29 09:49 UTC, Olenteva74 commented on src/components/PaymentLink/PaymentLink.jsx
> +        className="w-full textGradient text-transparent bg-clip-text flex gap-3 justify-center items-center before:w-6 before:h-6 before:flex before:justify-center before:items-start before:content-[
Убрала паддинги, теперь фокус на 100%

2023-09-29 09:53 UTC, Olenteva74 commented on src/app/[lang]/page.jsx
> +      <Donate donate={donate} />
Исправила

2023-09-29 10:08 UTC, Olenteva74 commented on src/components/PaymentDetail/PaymentDetail.jsx
> +          {copied ? (
Поставила setTimeout на 3 секунды

2023-09-29 13:17 UTC, Olenteva74 commented on src/components/TabContent/Privat24/Privat24.jsx
> +        </h3>
https://monosnap.com/file/toGVAUSORshjCdTRBW5He5KwfVB73b
Слева знак из текста, справа - через символьную подстановку

2023-09-29 13:21 UTC, Olenteva74 commented on src/components/PaymentDetail/PaymentDetail.jsx
> +              })}
Заменила

2023-09-29 13:22 UTC, Olenteva74 commented on src/components/PaymentDetail/PaymentDetail.jsx
> +              className="flex justify-center items-center w-full h-full opacity-75 hover:opacity-100 transition duration-300 cursor-pointer"
focus добавила

2023-09-29 13:24 UTC, Olenteva74 commented on src/components/TabContent/Mono/Mono.jsx
> +    <div className="flex flex-col gap-10 justify-center items-center md:flex-row xl:flex-row-reverse xl:gap-0 md:justify-between">
Поменяла

2023-09-29 13:28 UTC, Olenteva74 commented on src/components/TabContent/Mono/Mono.jsx
> +        <PaymentLink title={link.title} url={link.url} />
Поменяла

2023-09-29 13:28 UTC, Olenteva74 commented on src/components/TabContent/Privat24/Privat24.jsx
> +        <PaymentLink title={link.title} url={link.url} />
Поменяла

2023-09-29 13:30 UTC, Olenteva74 commented on src/components/TabContent/Mono/Mono.jsx
> +        <QrCode />
Поменяла

2023-10-02 07:53 UTC, nadiakhoptiuk commented on src/components/PaymentLink/PaymentLink.jsx
> +        className="w-full textGradient text-transparent bg-clip-text flex gap-3 justify-center items-center before:w-6 before:h-6 before:flex before:justify-center before:items-start before:content-[
треба було падінги перенести на посилання, а не прибрати цілком, тепер кнопка геть не за макетом

2023-10-02 09:55 UTC, merged