Feature/about
SoftRyzen-internship/pure-water pull request #23
Opened 2023-09-27 20:26 UTC by BogdanGlazkov

2023-09-28 15:01 UTC, nadiakhoptiuk requested changes

2023-09-28 20:16 UTC, BogdanGlazkov commented on src/components/AboutCard/AboutCard.jsx
> +export const AboutCard = ({ data, index }) => {
+

2023-09-28 21:00 UTC, BogdanGlazkov commented on src/components/AboutCard/AboutCard.jsx
> +      } w-full h-full xl:w-[287px] px-5 md:px-6 py-6 xl:border-2 xl:border-tertiary rounded-10`}
Ні, всі по 24

2023-09-28 21:05 UTC, BogdanGlazkov commented on src/sections/About/About.jsx
> +    <section className="section xl:aboutBg pt-0 xl:pb-[156px]" id="about">
Я хочу ділити порівну, але у випадку з десктопом, я нижній падінг тут повністю забираю, щоб вмістити фоновий рисунок. Тоді у наступній секції верхній падінг поставимо 0

2023-09-29 12:54 UTC, nadiakhoptiuk commented on src/sections/About/About.jsx
> +    <section className="section xl:aboutBg pt-0 xl:pb-[156px]" id="about">
при скролі до наступної секції заголовок буде впритик до краю екрану

2023-09-29 14:50 UTC, nadiakhoptiuk requested changes

2023-09-29 14:50 UTC, nadiakhoptiuk commented on src/components/AboutCard/AboutCard.jsx
> +        index === 3 ? 'xl:h-[393px]' : 'xl:h-[629px]'
отут після зміни шрифта буде чуть менша висота, для останньої постав h-max, для трьох h-auto

2023-09-29 18:22 UTC, BogdanGlazkov commented on src/sections/About/About.jsx
> +    <section className="section xl:aboutBg pt-0 xl:pb-[156px]" id="about">
+

2023-09-29 18:38 UTC, BogdanGlazkov commented on src/components/AboutCard/AboutCard.jsx
> +        index === 3 ? 'xl:h-[393px]' : 'xl:h-[629px]'
Поставив висоту за оновленим макетом

2023-10-01 08:33 UTC, nadiakhoptiuk commented on src/components/AboutCard/AboutCard.jsx
> +        index === 3 ? 'xl:h-[393px]' : 'xl:h-[629px]'
а навіщо ставити фіксовану, якщо можна підігнати по контенту?

2023-10-01 08:43 UTC, nadiakhoptiuk requested changes

2023-10-01 08:43 UTC, nadiakhoptiuk commented on src/sections/About/About.jsx
> +      <div className="xl:hidden">
цей дів зайвий
можеш задати клас свайперу і вписати ці стилі через глобал

або рендер за умови !isDesktop (це все одно клієнтський компонент), треба глянути, якщо не моргатиме

2023-10-01 20:35 UTC, BogdanGlazkov commented on src/components/AboutCard/AboutCard.jsx
> +        index === 3 ? 'xl:h-[393px]' : 'xl:h-[629px]'
Якщо ставити за контентом, то всі картки будуть різної висоти. Не думаю що це гарна ідея

2023-10-02 07:08 UTC, BogdanGlazkov commented on src/components/AboutCard/AboutCard.jsx
> +        index === 3 ? 'xl:h-[393px]' : 'xl:h-[629px]'
+

2023-10-02 07:38 UTC, BogdanGlazkov commented on src/sections/About/About.jsx
> +      <div className="xl:hidden">
Для свайпера стилі hidden чомусь не працюють. Тому доводиться обгортати в дів.
Спробував рендер за умови !isDesktop через react-responsive, але компонент моргає

2023-10-02 10:50 UTC, nadiakhoptiuk commented on src/components/AboutSwiper/AboutSwiper.jsx
> +            className="!w-[279px] !h-[510px] md:!w-[287px] md:!h-[590px] border-2 border-tertiary rounded-10"
прибрати всі висоти, натомість поставити h-auto, всі слайди поплили зараз

2023-10-02 10:50 UTC, nadiakhoptiuk commented on src/sections/About/About.jsx
> +      <div className="xl:hidden">
через !important працює, зараз покажу

2023-10-02 11:03 UTC, merged