header + mobile menu
SoftRyzen-internship/pure-water pull request #24
Opened 2023-09-28 06:55 UTC by yuliahalaniuk

2023-09-28 13:40 UTC, BogdanGlazkov requested changes

2023-09-28 13:40 UTC, BogdanGlazkov commented on src/components/MobileMenu/MobileMenu.jsx
> +import { createPortal } from 'react-dom';
Це не react з одним дівом в html, createPortal тут не треба)

2023-09-28 13:40 UTC, BogdanGlazkov commented on src/components/MobileMenu/MobileMenu.jsx
> +  const [mounted, setMounted] = useState(false);
Замінити на isMenuOpen, setIsMenuOpen

2023-09-28 13:40 UTC, BogdanGlazkov commented on src/components/MobileMenu/MobileMenu.jsx
> +  useEffect(() => setMounted(true), []);
Цей useEffect тут не треба

2023-09-28 13:40 UTC, BogdanGlazkov commented on src/components/MobileMenu/MobileMenu.jsx
> +    };
На мобільних пристроях і планшетах немає клавіші Escape, тому цю перевірку можна прибрати

2023-09-28 13:40 UTC, BogdanGlazkov commented on src/components/MobileMenu/MobileMenu.jsx
> +  };
Цей код теж сюди не підходить. Моб меню у нас займає весь екран, оверлея немає

2023-09-28 13:40 UTC, BogdanGlazkov commented on src/components/MobileMenu/MobileMenu.jsx
> +    }),
isRequired

2023-09-28 13:40 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +  }).isRequired,
Прописати всі проптайпси

2023-09-28 13:45 UTC, BogdanGlazkov requested changes

2023-09-28 13:45 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +    openMenu: PropTypes.string,
5 isRequired

2023-09-28 13:56 UTC, BogdanGlazkov requested changes

2023-09-28 13:56 UTC, BogdanGlazkov commented on src/components/MobileMenu/MobileMenu.jsx
> +              aria-expanded={isMenuOpen}
Думаю це зайве. Якщо кнопку видно, то вона є доступна

2023-09-28 13:56 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +            aria-expanded={isMenuOpen}
Думаю це зайве. Якщо кнопку видно, то вона є доступна

2023-09-28 13:56 UTC, BogdanGlazkov commented on src/components/MobileMenu/MobileMenu.jsx
> +      window.addEventListener('keydown', onKeyDown);
Цей слухач також можна прибрати

2023-09-28 13:56 UTC, BogdanGlazkov commented on src/components/MobileMenu/MobileMenu.jsx
> +      window.removeEventListener('keydown', onKeyDown);
Цей слухач також можна прибрати

2023-09-28 14:16 UTC, BogdanGlazkov requested changes

2023-09-28 14:16 UTC, BogdanGlazkov commented on src/components/NavBar/NavBar.jsx
> +                } text-white/75 py-3 transition-colors  duration-300 cursor-pointer hover:text-white focus:text-white`}
У флекса вже встановлений gap, тому падінги не треба

2023-09-28 16:07 UTC, nadiakhoptiuk requested changes

2023-09-28 16:07 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +        <MobileMenu
мобільне меню рендерити тільки якщо це не десктоп, і якщо воно відкрите

2023-09-29 07:50 UTC, BogdanGlazkov approved these changes

2023-09-29 08:48 UTC, nadiakhoptiuk commented on src/components/MobileMenu/MobileMenu.jsx
> +            <div className="pt-32 w-auto inline-flex flex-col items-center gap-9">
не виправлено, меню не посередині екрану

2023-09-29 08:51 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +        <MobileMenu
використати react-responsive і рендерити меню якщо це не декстоп, бо воно продовжує висіти у дом дереві

2023-10-01 09:15 UTC, nadiakhoptiuk commented on src/components/MobileMenu/MobileMenu.jsx
> +            <div className="pt-32 w-auto inline-flex flex-col items-center gap-9">
https://prnt.sc/PzYXSD6ULJvY

подивитися по коду, як додають транзішини, щоб відкриття/закриття відбувалось плавно

2023-10-01 09:15 UTC, nadiakhoptiuk commented on src/components/MobileMenu/MobileMenu.jsx
> +            <div className="pt-32 w-auto inline-flex flex-col items-center gap-9">
навбар флексами відцентрувати посередині екрану

2023-10-02 15:17 UTC, merged