created footer
SoftRyzen-internship/pure-water pull request #25
Opened 2023-09-28 15:38 UTC by Olenteva74

Добрый день, пока вместо background-image поставила градиент

2023-09-29 08:21 UTC, nadiakhoptiuk requested changes

2023-09-29 08:21 UTC, nadiakhoptiuk commented on src/components/SocialLinks/SocialLinks.jsx
> +              className="w-full h-full text-white/75 hover:text-white focus:text-white transition duration-300 flex justify-center xl:justify-start items-center gap-3"
прибрати w-full з лінків для десктопа!, бо на футері є велике поле поза посиланням, яке є клікабельне

2023-09-29 08:21 UTC, nadiakhoptiuk commented on src/layout/Footer/Footer.jsx
> +          <div className="w-12 h-12 xl:hidden"></div>
що це за порожній дів?

2023-09-29 08:21 UTC, nadiakhoptiuk commented on src/layout/Footer/Footer.jsx
> +        <div className="flex justify-between">
навіщо додаткова обгортка, якщо ці стилі можна додати на контейнер?

2023-09-29 08:21 UTC, nadiakhoptiuk commented on src/layout/Footer/Footer.jsx
> +          <div className="hidden xl:block">
тут краще зробити рендер за умови (якщо десктоп - рендеримо навбар і всі ті діви, можливо окремими умовами), якщо моб і таблет - кнопка-бургер
використати можна react-responsive

всі ті елементи, які hidden, продовжують висіти у dom дереві

2023-09-29 08:21 UTC, nadiakhoptiuk commented on src/app/[lang]/globals.css
> +  background-position: center;
на мобільному позиція фону не центр - згідно з макетом

для таблета додати ще одне медіа правило і поставити позицію фону згідно з макетом, приблизно ось так:
https://prnt.sc/uwLsa_y8AjwV

2023-09-30 09:26 UTC, Olenteva74 commented on src/app/[lang]/globals.css
> +.footer {
Поменяла

2023-09-30 09:26 UTC, Olenteva74 commented on src/layout/Footer/Footer.jsx
> +    <section className="w-full h-[426px] md:h-[670px] xl:h-[1200px] pt-[170px] md:pt-[246px] xl:pt-[533px] pb-[30px] md:pb-10 xl:pb-20 footer text-white flex items-center">
Поменяла

2023-09-30 09:27 UTC, Olenteva74 commented on src/layout/Footer/Footer.jsx
> +    <section className="w-full h-[426px] md:h-[670px] xl:h-[1200px] pt-[170px] md:pt-[246px] xl:pt-[533px] pb-[30px] md:pb-10 xl:pb-20 footer text-white flex items-center">
Оставила паддинги

2023-09-30 09:27 UTC, Olenteva74 commented on src/components/CreatedBy/CreatedBy.jsx
> +    <div className="text-xs font-light xl:absolute xl:bottom-0 xl:left-[-312px]">
Заменила

2023-09-30 09:27 UTC, Olenteva74 commented on src/components/SocialLinks/SocialLinks.jsx
> +              className="w-full h-full text-white/75 hover:text-white focus:text-white transition duration-300 flex justify-center xl:justify-start items-center gap-3"
Поменяла

2023-09-30 09:27 UTC, Olenteva74 commented on src/layout/Footer/Footer.jsx
> +          <div className="w-12 h-12 xl:hidden"></div>
Это для мобильного меню

2023-09-30 09:29 UTC, Olenteva74 commented on src/layout/Footer/Footer.jsx
> +        <div className="flex justify-between">
Не смогла добавить стили в контейнер, убрала компонент, добавила класс container

2023-10-03 08:02 UTC, nadiakhoptiuk requested changes

2023-10-03 09:46 UTC, Olenteva74 commented on src/app/[lang]/globals.css
> +  background-image: url('/images/footer/footer_tab@1x.jpg');
В медиаправилах есть desk@2x

2023-10-03 09:46 UTC, Olenteva74 commented on src/layout/Footer/Footer.jsx
> +    <footer className="footer w-full pt-[138px] md:pt-[280px] xl:pt-[454px] pb-10 xl:pb-12 text-white">
Поменяла

2023-10-03 09:47 UTC, Olenteva74 commented on src/app/[lang]/globals.css
> +@media screen and (min-width: 1280px) {
Поменяла на 768

2023-10-03 09:47 UTC, Olenteva74 commented on src/app/[lang]/globals.css
> +    background-position: center;
Поменяла

2023-10-03 09:48 UTC, Olenteva74 commented on src/app/[lang]/globals.css
> +
Объединила

2023-10-03 09:48 UTC, Olenteva74 commented on src/layout/Footer/Footer.jsx
> +          <MobileMenu
Пропс поменяла

2023-10-03 13:01 UTC, nadiakhoptiuk commented on src/app/[lang]/globals.css
> +  background-image: url('/images/footer/footer_tab@1x.jpg');
це для ретіни, а нам треба для 2к, попрошу дизайнера

2023-10-03 13:01 UTC, nadiakhoptiuk commented on public/images/footer/footer_mob@1x.png
картинки для мобільного для футера прибрати

2023-10-03 13:06 UTC, Olenteva74 commented on public/images/footer/footer_mob@1x.png
Ok

2023-10-03 13:27 UTC, nadiakhoptiuk approved these changes

2023-10-03 13:27 UTC, merged