add images and icons for the project
SoftRyzen-internship/pure-water pull request #7
Opened 2023-09-20 08:16 UTC by Anna-Voronina

2023-09-20 08:50 UTC, BogdanGlazkov requested changes
yellow-blue-heart імпортувати у х2.
Всі іконки оптимізувати: прибрати width і height, прибрати id (можуть бути конфлікти, якщо 2 однакові id на сторінці), прибрати fill, щоб можна було змінити колір на ховері

2023-09-20 09:39 UTC, nadiakhoptiuk requested changes

2023-09-20 09:39 UTC, nadiakhoptiuk commented on public/images/footer/footer_mob@1x.png
як це зображення буде виглядати на екрані, ширшому за 320?
мабуть, використаємо з таблета, а це зайве

2023-09-20 09:39 UTC, nadiakhoptiuk commented on public/images/menu/menu_mob@2x.jpg
викачай одну на таблет (+ 2х + дві webp), на мобілку не треба окремо

2023-09-20 09:39 UTC, nadiakhoptiuk commented on public/images/hero/hero_mob@2x.jpg
для героя, я думаю, не варто викачувати мобільну версію, бо екрани можуть бути ширші, фото потягнуться більше за власний розмір.
поставимо з десктопа фото на декстоп і на таблет, а на мобілку - фото з таблета
(дуже бажано додати webp для фонових картинок)

2023-09-20 09:57 UTC, nadiakhoptiuk commented
> yellow-blue-heart імпортувати у х2. Всі іконки оптимізувати: прибрати width і height, прибрати id (можуть бути конфлікти, якщо 2 однакові id на сторінці), прибрати fill, щоб можна було змінити колір на ховері

поправка)

щодо іконок, які мають заливку градієнтом (стрілки):
я вже тут їх покрутила по-різному, і дослідила, що по факту у них опасіті змінюється з 75 на 100 при ховері.
тому викачуємо ті стрілки https://prnt.sc/lar_JOoPxHbe версію для ховера, і будемо їм анімувати опасіті

2023-09-20 19:01 UTC, Anna-Voronina commented
Видалила зайве та додала все відповідно до коментарів)

2023-09-21 07:51 UTC, BogdanGlazkov requested changes
У Лого видалити clipPath id="clip0_431_741">
<rect width="32" height="52" fill="white"/>
</clipPath ,
бо на мобільному розміри менші, і будуть конффлікти, бо 2 лого на сторінці (у хедері та футері) з одніковим id

2023-09-21 08:41 UTC, nadiakhoptiuk commented
не можна видаляти width i height з svg

2023-09-21 10:35 UTC, Anna-Voronina commented
Повернула висоту та ширину іконкам та додала файл svgr.config.js)

2023-09-21 11:44 UTC, nadiakhoptiuk approved these changes

2023-09-21 11:46 UTC, merged